version: "3.7"

services:

  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    image: nginx:latest
    ports:
      - ${PROJECT_HTTP_PORT}:80
    volumes:
      - ${ROOT_DIR}:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    container_name: ${APP_NAME}-app
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${APP_NAME}
    volumes:
      - ${ROOT_DIR}:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:latest
    restart: always
    ports:
        - "${DB_PORT}:5432"
    environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - /docker/.data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: powerdmarc-redis
    restart: always
    image: redis:3
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge